sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_9b054dc6b00b_key -iv $encrypted_9b054dc6b00b_iv -in fibo-k8s-account.json.enc -out fibo-k8s-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file fibo-k8s-account.json
    - gcloud config set project fibo-8ks-291212
    - gcloud config set compute/zone europe-west2-a
    - gcloud container clusters get-credentials fibo-k8s-cluster
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker build -t dbernat/fibotest -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dbernat/fibotest npm run test

deploy:
    provider: script
    script: bash ./deploy.sh    
    on: 
        branch: master